name: persona
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.5
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_local_notifications: ^22.3.1
  timezone: ^0.11.1
  google_sign_in_all_platforms: 2.0.3
  flutter_dotenv: ^6.0.1
  googleapis: ^14.0.0
  table_calendar: ^3.2.0
  geolocator: ^14.1.0
  google_maps_flutter: ^2.18.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  file_picker: 13.1.0
  path_provider: ^2.1.5
  firebase_auth_mocks: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - images/persona_anime_butterflies.png