// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeSPECowxDnHsde_dJfg4lajGkR_SXyBw',
    appId: '1:596791568376:web:9b0a3bc8eb119e7dabd80d',
    messagingSenderId: '596791568376',
    projectId: 'persona-509608',
    authDomain: 'persona-509608.firebaseapp.com',
    databaseURL: 'https://persona-509608-default-rtdb.firebaseio.com',
    storageBucket: 'persona-509608.firebasestorage.app',
    measurementId: 'G-5WMPWMENMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgcP1biyiRNmGTKoyxGrfUvH56yDOPmJM',
    appId: '1:596791568376:android:42eb142f7fa6c79eabd80d',
    messagingSenderId: '596791568376',
    projectId: 'persona-509608',
    databaseURL: 'https://persona-509608-default-rtdb.firebaseio.com',
    storageBucket: 'persona-509608.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD17y9nLHjMEIb3UUWfverUHx4I0KVy9JM',
    appId: '1:596791568376:ios:a0e4f6af0d9aeb5dabd80d',
    messagingSenderId: '596791568376',
    projectId: 'persona-509608',
    databaseURL: 'https://persona-509608-default-rtdb.firebaseio.com',
    storageBucket: 'persona-509608.firebasestorage.app',
    androidClientId: '596791568376-hlcft7io3qar19rcfev96cesjm2e4ou7.apps.googleusercontent.com',
    iosBundleId: 'com.example.persona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD17y9nLHjMEIb3UUWfverUHx4I0KVy9JM',
    appId: '1:596791568376:ios:a0e4f6af0d9aeb5dabd80d',
    messagingSenderId: '596791568376',
    projectId: 'persona-509608',
    databaseURL: 'https://persona-509608-default-rtdb.firebaseio.com',
    storageBucket: 'persona-509608.firebasestorage.app',
    androidClientId: '596791568376-hlcft7io3qar19rcfev96cesjm2e4ou7.apps.googleusercontent.com',
    iosBundleId: 'com.example.persona',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeSPECowxDnHsde_dJfg4lajGkR_SXyBw',
    appId: '1:596791568376:web:6d7f48da7b78d0d9abd80d',
    messagingSenderId: '596791568376',
    projectId: 'persona-509608',
    authDomain: 'persona-509608.firebaseapp.com',
    databaseURL: 'https://persona-509608-default-rtdb.firebaseio.com',
    storageBucket: 'persona-509608.firebasestorage.app',
    measurementId: 'G-KL4QG9HCW9',
  );
}
